require("vincent.plugins-setup")
require("vincent.core.options")
require("vincent.core.keymaps")
require("vincent.core.colorscheme")
require("vincent.plugins.comment")
require("vincent.plugins.nvim-tree")
require("vincent.plugins.lualine")
require("vincent.plugins.telescope")
require("vincent.plugins.nvim-cmp")
require("vincent.plugins.lsp.mason")
require("vincent.plugins.lsp.lspaga")
require("vincent.plugins.lsp.lspconfig")
-- require("vincent.plugins.lsp.null-ls")
require("vincent.plugins.autopairs")
require("vincent.plugins.treesitter")
require("vincent.plugins.gitsigns")
